version: "3.3"

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - bookstore-volume:/var/lib/mysql
# Names our volume
volumes:
  bookstore-volume:
